/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1b9afd03-9767-42c8-911e-7c7a601d79e5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IuYZVD4X4",
    "aws_user_pools_web_client_id": "1iq8o0hlrqro29kvfge26qhdvk",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "BIRTHDATE",
        "EMAIL",
        "NAME",
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "FuturePathUsersDemo-demo",
            "region": "us-east-1"
        },
        {
            "tableName": "FuturePathLeaderboardsDemo-demo",
            "region": "us-east-1"
        },
        {
            "tableName": "FuturePathAnnouncementsDemo-demo",
            "region": "us-east-1"
        },
        {
            "tableName": "FuturePathNotificationsDemo-demo",
            "region": "us-east-1"
        },
        {
            "tableName": "FuturePathParentsLeaderboardDemo-demo",
            "region": "us-east-1"
        },
        {
            "tableName": "FuturePathSchoolsDemo-demo",
            "region": "us-east-1"
        },
        {
            "tableName": "FuturePathMentorInvitesDemo-demo",
            "region": "us-east-1"
        },
        {
            "tableName": "FuturePathMentors-demo",
            "region": "us-east-1"
        },
        {
            "tableName": "FuturePathMentorInvites-demo",
            "region": "us-east-1"
        },
        {
            "tableName": "FuturePathTutors-demo",
            "region": "us-east-1"
        },
        {
            "tableName": "FuturePathTutorInvites-demo",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "FuturePathAPIDemo",
            "endpoint": "https://lx147yqkva.execute-api.us-east-1.amazonaws.com/demo",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
